kind: Service
apiVersion: v1
metadata:
  name: appv1
spec:
  type: LoadBalancer
  selector:
    app: appv1
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv1
  labels:
    app: appv1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appv1
  template:
    metadata:
      labels:
        app: appv1
    spec:
      containers:
      - name: appv1
        image: us.gcr.io/sincere-chariot-260312/app1@sha256:24b8bd3a7ca8ea802c061d933f75115a95d129187e82b4c540bdea2cebba5776
        ports:
        - containerPort: 80
